version: "3.7"
services:
    db:
        image: mysql:latest
        container_name: mysql_db
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        hostname: mysql_db
        ports:
            - "3307:3306"
        env_file:
            - mysql.env
        networks:
            - mynet
        volumes:
            - mysqldata/var/lib/mysql
    airflow-engine:
        build: .
        container_name: airflow
        #command: tail -f /dev/null
        command: /bin/sh -c "/root/airflow/setup.sh"
        depends_on: 
            - db
        init: true
        volumes:
            - airflowdata/root/airflow/
        ports:
            - "8080:8080"
        environment:
            - PYTHONPATH=/root/airflow/
        env_file:
            - mysql.env
        networks:
            - mynet
networks:
    mynet:
volumes:
    airflowdata:
    mysqldata: 
